pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    bat "docker build -f 02-primer-pipeline/Dockerfile -t node${BUILD_ID} 02-primer-pipeline"
                }
            }
        }
        stage('docker push') {
            steps {
                script {            
                    bat "docker push node${BUILD_ID}"
                }
            }
        }
    }
}
